version: "3.4"

services:
  # web:
  #   container_name: web
  #   build:
  #     context: .
  #     dockerfile: ./apps/web/Dockerfile
  #   restart: always
  #   ports:
  #     - 3000:3000

  time-based:
    container_name: time-based
    build:
      context: .
      dockerfile: ./apps/time-based/Dockerfile
    restart: always
    ports:
      - 3001:3000

  on-demand:
    container_name: on-demand
    build:
      context: .
      dockerfile: ./apps/on-demand/Dockerfile
    restart: always
    ports:
      - 3002:3000